routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\GuidelineController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BackendUserController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\UserDetailController;
use App\Http\Controllers\PregnantCodeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// Route::get('login', 'App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'App\Http\Controllers\Auth\LoginController@login');
// Route::post('logout', 'App\Http\Controllers\Auth\LoginController@logout')->name('logout');

// // Registration Routes...
// Route::get('register', 'App\Http\Controllers\Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'App\Http\Controllers\Auth\RegisterController@register');
// //Password Routes
// Route::get('password/reset', 'App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
// Route::post('password/email', 'App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
// Route::get('password/reset/{token}', 'App\Http\Controllers\Auth\ResetPasswordController@showResetForm');
// Route::post('password/reset', 'App\Http\Controllers\Auth\ResetPasswordController@reset');
Auth::routes();


Route::middleware('auth')->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/user/list', [UserController::class, 'list'])->name('user.list');
    Route::get('setting', [SettingController::class, 'index'])->name('setting.index');
    Route::post('updateUserStatus/{id}',[UserDetailController::class, 'updateUserStatus'])->name('user.updateUserStatus');
    Route::get('updateBackendUserStatus/{id}',[UserController::class, 'updateBackendUserStatus'])->name('user.updateBackendUserStatus');
    Route::post('sendSms',[UserDetailController::class, 'sendSms'])->name('user.sendSms');
    Route::post('guideline/delete/{id}', [GuidelineController::class, 'destroy']);
    Route::resource('guideline', GuidelineController::class);
    Route::resource('user', UserController::class);
    Route::resource('back-end', BackendUserController::class);
    Route::resource('topic', TopicController::class);
    Route::resource('type', TypeController::class);


    Route::prefix('code')->as('code.')->group(function () {
        Route::post('generate', [PregnantCodeController::class, 'generate'])->name('generate');
        Route::get('exportAll', [PregnantCodeController::class, 'exportAll'])->name('exportAll');
        Route::get('exportUsedCode', [PregnantCodeController::class, 'exportUsedCode'])->name('exportUsedCode');
        Route::get('exportUnusedCode', [PregnantCodeController::class, 'exportUnusedCode'])->name('exportUnusedCode');
    });

    Route::resource('pregnant-code', PregnantCodeController::class);



});

app/Models/BackendUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BackendUser extends Model
{
    use HasFactory;
}

app/Http/Controllers/BackendUserController.php
<?php

namespace App\Http\Controllers;

use App\Models\BackendUser;
use Illuminate\Http\Request;
use App\Models\User;
use Hash;
use App\Mail\WelcomeAdminUser;
use Illuminate\Support\Facades\Mail;

class BackendUserController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('is_backend_user', true)->get();
        return view('backend_user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateData($request);

        $is_backend_user = false;
        $is_super_admin = false;

        if ($request->is_backend_user) {
            $is_backend_user = true;
        }

        if ($request->is_super_admin) {
            $is_super_admin = true;
        }

        $password = $request->password;

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'is_backend_user' => $is_backend_user,
            'back_end_contact' => $request->contact,
            'is_super_admin' => $is_super_admin,
        ]);

        Mail::to($user->email)->send(new WelcomeAdminUser($user, $password));

        if($user){
            return redirect()->back()->with('success', 'Successfully registered!');
        }

        return redirect()->back()->with('error', 'Ops! Something went wrong.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\BackendUser  $backendUser
     * @return \Illuminate\Http\Response
     */
    public function show(BackendUser $backendUser)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\BackendUser  $backendUser
     * @return \Illuminate\Http\Response
     */
    public function edit(BackendUser $backendUser)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\BackendUser  $backendUser
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BackendUser $backendUser)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\BackendUser  $backendUser
     * @return \Illuminate\Http\Response
     */
    public function destroy(BackendUser $backendUser)
    {
        //
    }

    public function validateData($data)
    {
        $this->validate($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'contact' => ['required', 'numeric'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
    }
}

resources/views/backend_user/index.blade.php
@extends('layouts.app')

@section('current-page')
Admin
@endsection

@section('content')
<div class="card card-plain">
    <div class="card-header">
        <h1 class="card-title">Admin</h1>
        <p class="card-category">Manage Admins</p>
        <div class="card-body">

            <div class="row">
                {{-- Registration Form--}}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Register an admin</h5>
                            <div class="card-body">
                                <form action="{{ route('back-end.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <input type="hidden" name="is_backend_user" value="1">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Name</label>
                                            <input type="text" class="form-control @error('name') is-invalid @enderror"
                                                name="name">
                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="text" class="form-control @error('email') is-invalid @enderror"
                                                name="email">
                                            @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="contact">Contact</label>
                                            <input type="text" class="form-control @error('contact') is-invalid @enderror"
                                                name="contact">
                                            @error('contact')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="password">Password</label>
                                            <input type="text"
                                                class="form-control @error('password') is-invalid @enderror"
                                                name="password">
                                            @error('password')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="password_confirmation">Confirm Password</label>
                                            <input type="text"
                                                class="form-control @error('password_confirmation') is-invalid @enderror"
                                                name="password_confirmation">
                                            @error('password_confirmation')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Register</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                {{-- End Registration Form--}}

                {{-- Back End User List --}}
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Admin List</h5>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="text-primary">
                                        <th>#</th>
                                        <th>NAME</th>
                                        <th>EMAIL</th>
                                        <th>Contact #</th>
                                        <th>IS SUPER USER ?</th>
                                        <th>ACTION</th>
                                    </thead>
                                    <tbody>
                                        @php
                                            $i = 1;
                                        @endphp
                                        @foreach ($users as $user)
                                            <tr>
                                                <td>{{ $i++ }}</td>
                                                <td>{{ $user->name }}</td>
                                                <td>{{ $user->email }}</td>
                                                <td>{{ $user->back_end_contact }}</td>
                                                <td>{{ $user->is_super_admin == true ? "YES" : "NO" }}</td>
                                                <td >
                                                    @if ($user->is_super_admin == true)
                                                        <button class="btn btn-secondary" disabled><i class="nc-icon nc-box"></i></button>
                                                    @else

                                                        @if ($user->status)
                                                            <a href="{{ route('user.updateBackendUserStatus', $user->id ) }}" class="btn btn-danger">Deactivate&nbsp;<i class="nc-icon nc-simple-remove"></i></a>
                                                        @else
                                                            <a href="{{ route('user.updateBackendUserStatus', $user->id ) }}" class="btn btn-success">Activate&nbsp;<i class="nc-icon nc-check-2"></i></a>
                                                        @endif

                                                        <button class="btn btn-danger" onclick="removeType({{ $user->id }})"><i class="nc-icon nc-box"></i></button>
                                                    @endif

                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
@endsection