routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\GuidelineController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BackendUserController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\UserDetailController;
use App\Http\Controllers\PregnantCodeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// Route::get('login', 'App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'App\Http\Controllers\Auth\LoginController@login');
// Route::post('logout', 'App\Http\Controllers\Auth\LoginController@logout')->name('logout');

// // Registration Routes...
// Route::get('register', 'App\Http\Controllers\Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'App\Http\Controllers\Auth\RegisterController@register');
// //Password Routes
// Route::get('password/reset', 'App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
// Route::post('password/email', 'App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
// Route::get('password/reset/{token}', 'App\Http\Controllers\Auth\ResetPasswordController@showResetForm');
// Route::post('password/reset', 'App\Http\Controllers\Auth\ResetPasswordController@reset');
Auth::routes();


Route::middleware('auth')->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/user/list', [UserController::class, 'list'])->name('user.list');
    Route::get('setting', [SettingController::class, 'index'])->name('setting.index');
    Route::post('updateUserStatus/{id}',[UserDetailController::class, 'updateUserStatus'])->name('user.updateUserStatus');
    Route::get('updateBackendUserStatus/{id}',[UserController::class, 'updateBackendUserStatus'])->name('user.updateBackendUserStatus');
    Route::post('sendSms',[UserDetailController::class, 'sendSms'])->name('user.sendSms');
    Route::post('guideline/delete/{id}', [GuidelineController::class, 'destroy']);
    Route::resource('guideline', GuidelineController::class);
    Route::resource('user', UserController::class);
    Route::resource('back-end', BackendUserController::class);
    Route::resource('topic', TopicController::class);
    Route::resource('type', TypeController::class);


    Route::prefix('code')->as('code.')->group(function () {
        Route::post('generate', [PregnantCodeController::class, 'generate'])->name('generate');
        Route::get('exportAll', [PregnantCodeController::class, 'exportAll'])->name('exportAll');
        Route::get('exportUsedCode', [PregnantCodeController::class, 'exportUsedCode'])->name('exportUsedCode');
        Route::get('exportUnusedCode', [PregnantCodeController::class, 'exportUnusedCode'])->name('exportUnusedCode');
    });

    Route::resource('pregnant-code', PregnantCodeController::class);



});

app/Models/Guideline.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Guideline extends Model
{
    use HasFactory;

    public function topics()
    {
        return $this->belongsToMany(Topic::class);
    }

    public function type()
    {
        return $this->belongsTo(Type::class);
    }
}

app/Http/Controllers/API/GuidelinesController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Guideline;
use App\Models\Topic;

class GuidelinesController extends Controller
{
    public function index()
    {
        // $guidelines = Guideline::where('published', true)->with('topics', 'type')->orderBy('created_at', 'DESC')->get();
        $guidelines = array();

        $events = Topic::where('name', 'Events')->with(['guidelines' => function($query){
            $query->orderBy('created_at', 'DESC');
        }])->get();

        foreach ($events as $event) {
            $guidelines['events'] = $event->guidelines;
        }

        $tips = Topic::where('name', 'Tips')->with(['guidelines' => function($query){
            $query->orderBy('created_at', 'DESC');
        }])->get();

        foreach ($tips as $tip) {
            $guidelines['tips'] = $tip->guidelines;
        }

        $announcements = Topic::where('name', 'Announcements')->with(['guidelines' => function($query){
            $query->orderBy('created_at', 'DESC');
        }])->get();

        foreach ($announcements as $announcement) {
            $guidelines['announcements'] = $announcement->guidelines;
        }

        return response()->json(['guidelines' => $guidelines], 200);
    }

    public function show($id)
    {
        try {

            $guideline = Guideline::where('id', $id)->with('topics', 'type')->get();

            return response()->json([
                'success' => true,
                'guideline' => $guideline
            ]);

        } catch (\Throwable $th) {
            return response()->json([
                'success' => false,
                'message' => 'error',
            ]);
        }
    }
}

app/Http/Controllers/GuidelineController.php
<?php

namespace App\Http\Controllers;

use App\Models\Guideline;
use Illuminate\Http\Request;
use App\Models\Type;
use App\Models\Topic;
use App\Models\Attachment;
use Log;
use App\Models\UserFMCToken;
use App\Models\UserDetails;


class GuidelineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $guidelines = Guideline::orderBy('updated_at', 'DESC')->get();
        return view('guidelines.index', compact('guidelines'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = Type::all();
        $topics = Topic::all();
        return view('guidelines.create', compact('types', 'topics'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request;
        $this->validateData($request);
        try {
            $guideline = $this->saveGuideline($request);


            // Push Notification on mobile app
            $registration_ids = [];
            $forSms = [];

            if ($guideline->target_users == 'general') {
                $user_fmc_token = UserFMCToken::all();

                foreach ($user_fmc_token as $item) {
                    $registration_ids[] = $item->_fmc_token;
                }

                $userSMS = UserDetails::where('status', true)->get();

                foreach ($userSMS as $item) {
                    $forSms[] = $item->contact_number;
                }
            }elseif ($guideline->target_users == '1') {
                $users = UserDetails::where([['is_pregnant', true], ['status', true]])->with('user_fmc')->get();
                // return $users;
                foreach ($users as $item) {
                    if ($item->user_fmc->_fmc_token) {
                        $registration_ids[] = $item->user_fmc->_fmc_token;
                    }
                    $forSms[] = $item->contact_number;

                }
            } else {
                $users = UserDetails::where([['is_pregnant', false], ['status', true]])->with('user_fmc')->get();

                foreach ($users as $item) {
                    $registration_ids[] = $item->user_fmc->_fmc_token;
                    $forSms[] = $item->contact_number;
                }
            }


            $authorization_key = "AAAAB220scU:APA91bEUS8wSzeUh905t8NBCge0CuyQKS41ND09sTD6Xwcmwa5PlRFSQaTWJYWWLNFbb5Ab8yVw0DLvgYdXFrfpQn9tXQATmma4kH07iVc6rOybCLqhxXLE78X_cFuz9df2GToGLp5S8";

            $finalPostArray = array('registration_ids' => $registration_ids,
                                    'notification' => array('body' => 'There\'s a new guideline posted with a title "'. $guideline->title .'". To know more about it, please check it on your PHC app dashboard for more details.',
                                                            'title' => 'New Posted Guidelines',
                                                            "image"=> asset($guideline->banner_path) ),
                                    "data"=> array("click_action"=> "FLUTTER_NOTIFICATION_CLICK",
                                                    "sound"=> "default",
                                                    "status"=> "done"));

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL,"https://fcm.googleapis.com/fcm/send");
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS,json_encode($finalPostArray));  //Post Fields
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json', 'Authorization: key='.$authorization_key));
            $server_output = curl_exec ($ch);
            curl_close ($ch);
            // return $server_output;

            // End Push Notification on mobile app

            // SMS NOtification
            $sender = config('services.sms_sender');
            $sms_api_key = config('services.sms_api_key');
            $sms_api_secret = config('services.sms_api_secret');


            $pre_define_sms_user = 'There\'s a new guideline posted with a title "'. $guideline->title .'". To know more about it, please check it on your PHC app dashboard for more details.';
            $user_sms = str_replace(" ", "%20", $pre_define_sms_user);

            foreach ($forSms as $item) {

            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, "https://api.promotexter.com/sms/send?apiKey=".$sms_api_key."&apiSecret=".$sms_api_secret."&from=".$sender."&to=".$item."&text=".$user_sms);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
            curl_setopt($ch, CURLOPT_HEADER, FALSE);

            curl_setopt($ch, CURLOPT_POST, TRUE);

            $response = curl_exec($ch);
            curl_close($ch);

                # code...
            }

            // End SMS NOtification





            return redirect()->route('guideline.show', $guideline->id)->with('success', 'Post was successfully created!');
        } catch (\Throwable $th) {
            Log::info("Error while saving Guideline. Error at : " .$th);
            return redirect()->route('guideline.index')->with('error', 'Ops! Something went wrong.');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Guideline  $guideline
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $guideline = Guideline::where('id', $id)->with('type', 'topics')->first();
        // return $guideline;
        $types = Type::all();
        $topics = Topic::all();
        return view('guidelines.show', compact('guideline', 'types', 'topics'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Guideline  $guideline
     * @return \Illuminate\Http\Response
     */
    public function edit(Guideline $guideline)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Guideline  $guideline
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // return $request;

        if ($request->post_type == 1) {
            $validate = $this->validate($request, [
                'title' => ['required', 'string'],
                'subtitle' => ['required', 'string'],
                'content' => ['required'],
            ]);
        }else {
            $validate = $this->validate($request, [
                'title' => ['required', 'string'],
                'subtitle' => ['required', 'string'],
            ]);
        }

        try {


            $guideline = $this->updateGuideline($request, $id);

            return redirect()->route('guideline.show', $guideline->id)->with('success', 'Post was successfully updated!');
        } catch (\Throwable $th) {
            Log::info("Error while saving Guideline. Error at : " .$th);
            return redirect()->route('guideline.index')->with('error', 'Ops! Something went wrong.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Guideline  $guideline
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Guideline::find($id)->delete($id);

        return redirect()->route('guideline.index')->with('success', 'Guideline post was successfully removed!');
    }

    public function validateData($data)
    {
        if ($data->post_type == 1) {
            $validate = $this->validate($data, [
                'title' => ['required', 'string'],
                'subtitle' => ['required', 'string'],
                'content' => ['required'],
                'banner' => ['required'],
            ]);
        }else {
            $validate = $this->validate($data, [
                'title' => ['required', 'string'],
                'subtitle' => ['required', 'string'],
                'banner' => ['required'],
                'attachment' => ['required'],
            ]);
        }
    }



    public function saveGuideline($data)
    {
        $guideline = new Guideline;


        $guideline->target_users = $data->target_users;
        $guideline->title = $data->title;
        $guideline->subtitle = $data->subtitle;
        $guideline->content = $data->content;

        // for banner
        $this->saveBanner($data, $guideline);

        // for post type
        $this->attachType($data, $guideline);

        // for attachment/s
        $this->saveAttachments($data, $guideline);
        $guideline->save(); //save data



        // for post topics
        $this->attachTopics($data, $guideline);



        return $guideline;
    }

    public function updateGuideline($data, $id)
    {
        $guideline = Guideline::findOrFail($id);


        $guideline->target_users = $data->target_users;
        $guideline->title = $data->title;
        $guideline->subtitle = $data->subtitle;
        $guideline->content = $data->content;

        // for banner
        $this->saveBanner($data, $guideline);

        // for post type
        $this->attachType($data, $guideline);

        // for attachment/s
        $this->saveAttachments($data, $guideline);

        $guideline->save(); //save data

        // for post topics
        $this->attachTopics($data, $guideline);



        return $guideline;
    }

    public function saveBanner($data, $guideline)
    {
        if($data->banner){
            $filename = $data->banner->getClientOriginalName();

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Type;
use App\Models\Topic;

class SettingController extends Controller
{
    public function index()
    {
        $types = Type::with('guidelines')->get();
        $topics = Topic::with('guidelines')->get();

        $fix_topic_ids = [1,2,3];
        $fix_type_ids = [1,2];

        return view('settings.index', compact('types', 'topics', 'fix_topic_ids', 'fix_type_ids'));
    }
}

resources/views/settings/guideline/topic.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">TOPIC</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    {{-- <div class="col-md-4">
                        <div class="card card-plain">
                            <form action="{{ route('topic.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-header">
                                    <h5 class="card-title">Create Topic</h5>
                                </div>
                                <div class="card-body">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label for="topic_name">Topic Name</label>
                                            <input type="text" class="form-control @error('topic_name') is-invalid @enderror" name="topic_name">
                                            @error('topic_name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Add</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div> --}}
                    <div class="col-md-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h5 class="card-title">Topic List</h5>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead class="text-primary">
                                            <th>ID</th>
                                            <th>TOPIC</th>
                                            <th># OF RELATED GUIDELINES</th>
                                            {{-- <th>ACTION</th> --}}
                                        </thead>
                                        <tbody>
                                            @foreach ($topics as $topic)
                                                <tr>
                                                    <td>{{ $topic->id }}</td>
                                                    <td>{{ $topic->name }}</td>
                                                    <td>{{ count($topic->guidelines) }}</td>
                                                    {{-- <td>
                                                        <button class="btn btn-danger" onclick="removeTopic({{ $topic->id }})"
                                                    @foreach ($fix_topic_ids as $g_topic )
                                                        {{$g_topic == $topic->id ? 'disabled': ''}}
                                                    @endforeach><i class="nc-icon nc-simple-remove"></i></button>
                                                    </td> --}}
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/settings/guideline/type.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">TYPE</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    {{-- <div class="col-md-4">
                        <div class="card card-plain">
                            <form action="{{ route('type.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-header">
                                    <h5 class="card-title">Create Type</h5>
                                </div>
                                <div class="card-body">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label for="type_name">Type Name</label>
                                            <input type="text" class="form-control @error('type_name') is-invalid @enderror" name="type_name">
                                            @error('type_name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Add</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div> --}}
                    <div class="col-md-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h5 class="card-title">Type List</h5>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead class="text-primary">
                                            <th>ID</th>
                                            <th>Type</th>
                                            <th># OF RELATED GUIDELINES</th>
                                            {{-- <th>ACTION</th> --}}
                                        </thead>
                                        <tbody>
                                            @foreach ($types as $type)
                                                <tr>
                                                    <td>{{ $type->id }}</td>
                                                    <td>{{ $type->name }}</td>
                                                    <td>{{ count($type->guidelines) }}</td>
                                                    {{-- <td>
                                                        <button class="btn btn-danger" onclick="removeType({{ $type->id }})"
                                                            @foreach ($fix_type_ids as $g_type )
                                                        {{$g_type == $type->id ? 'disabled': ''}}
                                                    @endforeach><i class="nc-icon nc-simple-remove"></i></button>
                                                    </td> --}}
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>