routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\GuidelineController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BackendUserController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\UserDetailController;
use App\Http\Controllers\PregnantCodeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// Route::get('login', 'App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'App\Http\Controllers\Auth\LoginController@login');
// Route::post('logout', 'App\Http\Controllers\Auth\LoginController@logout')->name('logout');

// // Registration Routes...
// Route::get('register', 'App\Http\Controllers\Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'App\Http\Controllers\Auth\RegisterController@register');
// //Password Routes
// Route::get('password/reset', 'App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
// Route::post('password/email', 'App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
// Route::get('password/reset/{token}', 'App\Http\Controllers\Auth\ResetPasswordController@showResetForm');
// Route::post('password/reset', 'App\Http\Controllers\Auth\ResetPasswordController@reset');
Auth::routes();


Route::middleware('auth')->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/user/list', [UserController::class, 'list'])->name('user.list');
    Route::get('setting', [SettingController::class, 'index'])->name('setting.index');
    Route::post('updateUserStatus/{id}',[UserDetailController::class, 'updateUserStatus'])->name('user.updateUserStatus');
    Route::get('updateBackendUserStatus/{id}',[UserController::class, 'updateBackendUserStatus'])->name('user.updateBackendUserStatus');
    Route::post('sendSms',[UserDetailController::class, 'sendSms'])->name('user.sendSms');
    Route::post('guideline/delete/{id}', [GuidelineController::class, 'destroy']);
    Route::resource('guideline', GuidelineController::class);
    Route::resource('user', UserController::class);
    Route::resource('back-end', BackendUserController::class);
    Route::resource('topic', TopicController::class);
    Route::resource('type', TypeController::class);


    Route::prefix('code')->as('code.')->group(function () {
        Route::post('generate', [PregnantCodeController::class, 'generate'])->name('generate');
        Route::get('exportAll', [PregnantCodeController::class, 'exportAll'])->name('exportAll');
        Route::get('exportUsedCode', [PregnantCodeController::class, 'exportUsedCode'])->name('exportUsedCode');
        Route::get('exportUnusedCode', [PregnantCodeController::class, 'exportUnusedCode'])->name('exportUnusedCode');
    });

    Route::resource('pregnant-code', PregnantCodeController::class);



});

app/Models/PregnantCode.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PregnantCode extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PregnantCodeController.php
<?php

namespace App\Http\Controllers;

use App\Models\PregnantCode;
use Illuminate\Http\Request;
use App\Exports\PregnantCodeExport;
use App\Exports\PregnantCodeUsedCodeExport;
use App\Exports\PregnantCodeUnuseCodeExport;

class PregnantCodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $codes = PregnantCode::with('user')->paginate(10);

        return view('pregnant_code.index', compact('codes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\PregnantCode  $pregnantCode
     * @return \Illuminate\Http\Response
     */
    public function show(PregnantCode $pregnantCode)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\PregnantCode  $pregnantCode
     * @return \Illuminate\Http\Response
     */
    public function edit(PregnantCode $pregnantCode)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\PregnantCode  $pregnantCode
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PregnantCode $pregnantCode)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\PregnantCode  $pregnantCode
     * @return \Illuminate\Http\Response
     */
    public function destroy(PregnantCode $pregnantCode)
    {
        //
    }

    public function generate(Request $request)
    {

        $unUseCode = PregnantCode::whereNull('user_id')->get();

        // return count($unUseCode)

        if (count($unUseCode) >= 0 && count($unUseCode) <= 10) {
            for ($i=0; $i < $request->number ; $i++) {
                # code...

                $generated_code = \Str::random(6);

                $check = PregnantCode::where('code', $generated_code)->first();
                while ($check) {
                    $generated_code = \Str::random(6);
                    $check = PregnantCode::where('code', $generated_code)->first();
                }
                $saveGeneratedCode = new PregnantCode;
                $saveGeneratedCode->code = $generated_code;
                $saveGeneratedCode->save();

            }

            return redirect()->route('pregnant-code.index');
        }
        return redirect()->back()->with('info', 'Please use the unused code first before generating new codes.');
    }

    public function exportAll()
    {
        $dateTimeExported = date('YmdHis');
        return (new PregnantCodeExport)->download('AllPregnantCode_'.$dateTimeExported.'.xlsx');
    }

    public function exportUsedCode()
    {
        $dateTimeExported = date('YmdHis');
        return (new PregnantCodeUsedCodeExport)->download('UsedPregnantCode_'.$dateTimeExported.'.xlsx');
    }

    public function exportUnusedCode()
    {
        $dateTimeExported = date('YmdHis');
        return (new PregnantCodeUnuseCodeExport)->download('UnusedPregnantCode_'.$dateTimeExported.'.xlsx');
    }
}

resources/views/pregnant_code/index.blade.php
@extends('layouts.app')

@section('current-page')
Code
@endsection

@section('content')
<div class="card card-plain">
    <div class="card-header">
        <h1 class="card-title">Codes</h1>
        <p class="card-category">View Code List</p>
        <div class="card-body">

            <div class="row">

                {{-- User List --}}
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Code List</h5>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-default" data-toggle="modal"
                                data-target="#generateCodeModal">
                                Generate Code
                            </button>
                            <button class="btn btn-primary" data-toggle="modal"
                            data-target="#exportModal">Export Code</button>

                            <!-- Modal -->
                            <div class="modal fade" id="generateCodeModal" tabindex="-1" role="dialog"
                                aria-labelledby="generateCodeModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <form action="{{route('code.generate')}}" method="POST">
                                        @csrf
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="generateCodeModalLabel">Number to be generate</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <input type="number" name="number" id="" class="form-control"
                                                    onkeypress="if ( isNaN( String.fromCharCode(event.keyCode) )) return false;">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Generate</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="exportModal" tabindex="-1" role="dialog"
                                aria-labelledby="exportModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exportModalLabel">Export Codes</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="d-flex justify-content-center">
                                                <a href="{{ route('code.exportUnusedCode')}}" class="btn btn-info mr-3">Unused Codes</a>
                                                <a href="{{ route('code.exportUsedCode')}}" class="btn btn-info mr-3">Used Codes</a>
                                                <a href="{{ route('code.exportAll')}}" class="btn btn-success mr-3">All Codes</a>
                                            </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body" style="margin: 2rem !important;">
                            <div class="table-responsive-lg">
                                <table class="table user_list">
                                    <thead class="text-primary">
                                        <th>Code</th>
                                        <th>Used By</th>
                                        <th>Used Date</th>
                                        <th>Created Date</th>
                                    </thead>
                                    <tbody>
                                        @foreach ($codes as $code)
                                            <tr>
                                                <td>{{ $code->code}}</td>
                                                <td>{{ getUserName($code->user_id) }}</td>
                                                <td>{{ $code->used_date != null ?  date("F d, Y h:m A", strtotime($code->used_date)) : '' }}</td>
                                                <td>{{ date("F d, Y", strtotime($code->created_at));  }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>

                                </table>
                                {!! $codes->links() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
@endsection